version: "3.8"

services:
  runner:
    image: custom-github-runner-mac:latest
    platform: linux/arm64
    restart: always
    environment:
      REPO: ${REPO}                # Format: owner/repo (e.g., csp-sidekick/your-monorepo)
      REG_TOKEN: ${REG_TOKEN}      # GitHub self-hosted runner registration token
      NAME: ${NAME}                # Any unique runner name (e.g., macos-docker-runner-1)
      CLOUDFLARE_API_TOKEN: ${CLOUDFLARE_API_TOKEN}
      CLOUDFLARE_ACCOUNT_ID: ${CLOUDFLARE_ACCOUNT_ID}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: "6"
          memory: 4G
        reservations:
          cpus: "2"
          memory: 2G
