version: "3.8"


services:
  runner1:
    build:
      context: .
      dockerfile: Dockerfile.mac
    image: github-runner:latest
    container_name: github-runner-1
    platform: linux/arm64
    restart: always
    environment:
      ORG: ${ORG}
      REG_TOKEN: ${REG_TOKEN}
      NAME: runner-1
      LABELS: deploy-1
      CLOUDFLARE_API_TOKEN: ${CLOUDFLARE_API_TOKEN}
      CLOUDFLARE_ACCOUNT_ID: ${CLOUDFLARE_ACCOUNT_ID}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - runner1-cache:/home/docker/actions-runner/_work
      - runner1-bin:/home/runner/actions-runner

  runner2:
    build:
      context: .
      dockerfile: Dockerfile.mac
    image: github-runner:latest
    container_name: github-runner-2
    platform: linux/arm64
    restart: always
    environment:
      ORG: ${ORG}
      REG_TOKEN: ${REG_TOKEN}
      NAME: runner-2
      LABELS: deploy-2
      CLOUDFLARE_API_TOKEN: ${CLOUDFLARE_API_TOKEN}
      CLOUDFLARE_ACCOUNT_ID: ${CLOUDFLARE_ACCOUNT_ID}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - runner2-cache:/home/docker/actions-runner/_work
      - runner2-bin:/home/runner/actions-runner

  runner3:
    build:
      context: .
      dockerfile: Dockerfile.mac
    image: github-runner:latest
    container_name: github-runner-3
    platform: linux/arm64
    restart: always
    environment:
      ORG: ${ORG}
      REG_TOKEN: ${REG_TOKEN}
      NAME: runner-3
      LABELS: deploy-3
      CLOUDFLARE_API_TOKEN: ${CLOUDFLARE_API_TOKEN}
      CLOUDFLARE_ACCOUNT_ID: ${CLOUDFLARE_ACCOUNT_ID}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - runner3-cache:/home/docker/actions-runner/_work
      - runner3-bin:/home/runner/actions-runner

volumes:
  runner1-cache:
  runner1-bin:
  runner2-cache:
  runner2-bin:
  runner3-cache:
  runner3-bin:
